### PR TITLE
fix a schema bug

### LINKED ISSUE #3: Wrong Schema
Apparently 

```
"aggregator":{"type":"filtered","aggregator":
                          {"type":"longSum"
                          ,"name":"qualityRows"
                          ,"fieldName":"count"}
                    ,"filter":
                          {"type":"not"
                          ,"field":{"type":"selector","dimension":"quality","value":null}}
```

Is ok for druid but doesn't pass the `cli-druid` aggregation schema (clj-druid.schemas.aggregation). Or more precisely it try to use aggregator schema instead of filtered aggregator schema

### PR DESCRIPTION
**Pull request by yogsototh**
Check this should resolve #3

### CODE REVIEW

File: src/clj_druid/schemas/aggregation.clj [hunk 1]
```diff
@@ -54,20 +54,15 @@
    :name s/Str
    :fieldName s/Str})
 
+(declare aggregation)
```
Comment (gbuisson) [inline src/clj_druid/schemas/aggregation.clj:57]: we need to find a better way to handle that

**Comment by gbuisson** [comment]
sounds good to me
